### ISSUE TITLE
Nginx configuration?

### ISSUE THREAD

**Issue by Andrioshe** [PrivateBin/docker-nginx-fpm-alpine#1]
Is there an example for configuring the nginx server?

Actually I am getting the error message in the docker container:

> 12#12: *7 connect() to [::]:9000 failed (99: Address not available) while connecting to upstream, client: 172.17.0.1, server: ..

I think It is because of the missing upstream for php-fpm but even with:

> upstream php {
    server 127.0.0.1:9000;
}

 it wont work at all

**Comment by elrido** [comment]
It should not be necessary to change the nginx configuration, as it is built to just work. The "Address not available" would make sense, if you had disabled IPv6 in your docker daemon. I have tested this image on two different docker setups, but I do have IPv6 on both of them (its the default configuration of docker and my network). You can check if this could be the problem by running "ip a" or "ifconfig" on your docker host and look for "inet6" addresses.

If there are none, this is the problem and you can you try rebuilding the container after replacing "[::]" by "0.0.0.0" in https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/master/etc/nginx/sites-available/site.conf.

**Comment by elrido** [comment]
I had used the network socket because it is the default for the php-fpm image that serves as the base. Using a unix socket instead should avoid the issue you encountered and slightly improve the performance.
