### ISSUE TITLE
Duplicates pemission-policy header

### ISSUE THREAD

**Issue by rugk** [PrivateBin/docker-nginx-fpm-alpine#105]
I guess the nginx config here causes it so I directly open it here:
> There was a duplicate Permissions-Policy header.

https://securityheaders.com/?q=privatebin.net&followRedirects=on

Its likely not a big problem, but it may be removed.

**Comment by elrido** [comment]
It's from two locations:
https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/17eaeeb67d9ca6bad12d12f5beb22017a2b1bf0c/etc/nginx/http.d/site.conf#L18
https://github.com/PrivateBin/privatebin.info-pelican/blob/5d9f2627c052402f80f371e5fc83386b48bf6d10/nginx.conf#L166

With the 1.4 release we also added it to the PHP service, so it's now triplicate.
https://github.com/PrivateBin/PrivateBin/blob/1a5eafe4244a45bd02e9bb666770191e1e027b3b/lib/Controller.php#L345

I'll raise PRs.
