### ISSUE TITLE
Don't push every day to latest

### ISSUE THREAD

**Issue by Zoey2936** [PrivateBin/docker-nginx-fpm-alpine#125]
It would be nice if the image gets only pushed if there are changes, at least to latest. It is very annoying to update my PrivateBin container every day and I don't see any reason to push the container daily, maybe to nightly or edge or something like this, no problem, but would it not be enough that latest get only pushed on a new release? Thanks!

**Comment by elrido** [comment]
It had been specifically requested that latest, nightly and edge be updated automatically, so they would use the latest alpine base images of their release, for those that prefer to track a single tag. We have since added a mechanism that raises merge requests when the alpine base image gets updated and so we can at that time also push a new tagged image, so there would be less of a need for that.

I personally prefer using explicitly versioned images, so I know when I apply upgrades and can track in git at what time what version of a software had been deployed. But yeah, different folks use different workflows that work for them.

**Comment by Zoey2936** [comment]
But why? Alpine doesn't get updates every day (excluding the edge tag)? Would it not enough the nightly and edge get pushed every day?
Could the please be at least a tag called stable or something like this, which only get pushed if a new privatebin version gets released?

**Comment by elrido** [comment]
Alpine packages get updated all the time during a release, mostly for security updates but also for severe bugfixes. So at any point in time we may have outdated packages in our released images.

We do offer a stable tag, in the form of the release version, which we do only update on major security issues (i.e. openssl or other core alpine packages). As is explained in the README:

> - `latest` is an alias of the latest pushed image, usually the same as `nightly`, but excluding `edge`
> - `nightly` is the latest released PrivateBin version on an upgraded Alpine release image, including the latest changes from the docker image repository
> - `edge` is the latest released PrivateBin version on an upgraded Alpine edge image
> - `1.5.0` contains PrivateBin version 1.5.0 on the latest tagged release of the docker image repository - gets updated when important security fixes are released for Alpine or upon new Alpine releases
> - `1.5.0-...` are provided for selecting specific, immutable images
> 
> If you update your images automatically via pulls, the `nightly` or `latest` are recommended. If you prefer to have control and reproducability or use a form of orchestration, the numeric tags are probably preferable. The `edge` tag offers a preview of software in future Alpine releases and as an early warning system to detect image build issues in these.

**Comment by Zoey2936** [comment]
> Alpine packages get updated all the time during a release, mostly for security updates but also for severe bugfixes. So at any point in time we may have outdated packages in our released images.

That's true, but I use over 70 different images and this is the only images which gets daily pushed


> We do offer a stable tag, in the form of the release version, which we do only update on major security issues (i.e. openssl or other core alpine packages). As is explained in the README:

Yes, but not with a static tag

Theoretically, I just could use the 1.5.0 tag and update it if I get an email from GitHub about a new privatebin release, but a stable tag would be better for my use case, can I create an PR adding a tag called "stable"?

**Comment by elrido** [comment]
So a "stable" that points to the latest versioned tag? Yes, that sounds like a good idea. I guess that should be done around here:
https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/8700dcd64eae858a094651f9ae6e3c850aa3dd7c/buildx.sh#L79
