### ISSUE TITLE
(Docker Installation) Text can't be saved

### ISSUE THREAD

**Issue by freakyy85** [PrivateBin/docker-nginx-fpm-alpine#129]
## Steps to reproduce

1. Normal Docker Image installation, forward using caddy
2. The directory on the HDD is: /srv/privatebin-data as shown (I switched to /srv/ and so $PWD should have pointed to that privatebin-data directory there)

### What happens
The problem is, that when I try to post a paste it says: Error when trying to save text.
My guess is that it doesnt have permission to save. What permissions do I have to give it? From which user?

### What should happen
Stuff should be savable :D

## Basic information

**Server address**: https://p.bitsnbytes.chat

**Server OS:** Ubuntu 22.04

**Webserver:** Caddy v2 as proxy, relaying to included nginx from the docker

**Browser:**

**PrivateBin version:** 1.5.1

I can reproduce this issue on <https://privatebin.net>: No

**Comment by elrido** [comment]
The [README.md of the container image](https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/master/README.md#running-the-image) (in the git repo and on the docker hub page) mentions:

> Note that the volume mounted must be owned by UID 65534 / GID 82. If you run the container in a docker instance with "userns-remap" you need to add your subuid/subgid range to these numbers.

Please let us know if that is what your problem turned out to be or if there is another issue at play.

**Comment by freakyy85** [comment]
this helped. thanks i didnt read that section. :)
