### ISSUE TITLE
migrating data from Filesystem to GCS

### ISSUE THREAD

**Issue by AzamAhmadloo** [PrivateBin/docker-nginx-fpm-alpine#136]
Hello 
I am planning to migrate my previous data from a Filesystem to GCS using `migrate` script but I am facing the following issue:

PHP Fatal error:  Uncaught Error: Class "Google\Cloud\Storage\StorageClient" not found in /var/www/lib/Data/GoogleCloudStorage.php:69

**Comment by elrido** [comment]
It sounds like it isn't correctly picking up the vendor directory location, when autoloading the Google classes. I'll investigate the cause of it and how it can be amended.

**Comment by elrido** [comment]
So far struggled reproducing this. Just to confirm, you are using either the `privatebin/nginx-fpm-alpine` (all-in-one) or `privatebin/gcs` images for the migration, right? All the other image flavours don't contain the GCS libraries and the above error would be expected in those.

**Comment by AzamAhmadloo** [comment]
> So far struggled reproducing this. Just to confirm, you are using either the `privatebin/nginx-fpm-alpine` (all-in-one) or `privatebin/gcs` images for the migration, right? All the other image flavours don't contain the GCS libraries and the above error would be expected in those.



I am building image using [this repo's Dockerfile](https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/master/Dockerfile).

**Comment by AzamAhmadloo** [comment]
I checked [this Dockerfile](https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/master/Dockerfile) and found the issue. 
I was about [moving bin direcgtory](https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/master/Dockerfile#L75) into the docker image.
