### ISSUE TITLE
Unable to update with watchtower

### ISSUE THREAD

**Issue by stanthewizzard** [PrivateBin/docker-nginx-fpm-alpine#137]
Hello

Apparently there is an issue with buildx

You should pin the buildx version to v0.9.1 to fix your images (Example: https://github.com/cilium/cilium/pull/23206)

Thanks

**Comment by elrido** [comment]
What is broken in the images and which image and tag specifically do you have an issue with?

**Comment by stanthewizzard** [comment]
This may be due to the recent buildx change due to the Github Ubuntu Runner being upgraded:

https://github.com/docker/build-push-action/issues/755

This results in images being pushed whose manifests cannot be parsed due to these issues:

https://github.com/moby/moby/issues/43126

https://github.com/docker/buildx/issues/1509

I didn't get time to verify via the API for a failing image (https://github.com/AnalogJ/scrutiny, specifically the collector) but the docker manifest inspect command does fail for it and docker buildx imagetools inspect shows that it's an oci image.

**Comment by stanthewizzard** [comment]
Apparently it's also possilbe to do that:

No need to pin to previous release v0.9.1, repo can just disable provenance as shown in https://github.com/docker/buildx/issues/1513#issuecomment-1398340039

Also OCI images are around for a few years now so I think Watchtower should support them instead.

**Comment by stanthewizzard** [comment]
From
https://github.com/docker/buildx/issues/1513#issuecomment-1398340039

This is a build option so in [build-push-action](https://github.com/docker/build-push-action/):

  -
    name: Build and push
    uses: docker/build-push-action@v3
    with:
      push: true
      provenance: false
      tags: user/app:latest
Or if you invoke buildx directly then docker buildx build --provenance false ....

**Comment by elrido** [comment]
Thank you for providing more details. If I understand correctly, the images themselves would work, even though they are now stored in a different format, but the manifest created by docker buildx now contains information that docker (on the clients) can't parse (`docker manifest inspect` command), which in turn prevents watchtower from finding the updated image. Reading the linked issues, it certainly sounds like disabling the "provinence" in our buildx command would be a feasible workaround till the various tools have sorted themselves out.

https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/7a8d0cdc04da9819f2c924eaf9245bfef0409e2d/buildx.sh#L24-L30

**Comment by elrido** [comment]
Let me know if this works out after the nightly build at midnight (UTC) pushes the next image.

**Comment by stanthewizzard** [comment]
I'll check
thanks

**Comment by stanthewizzard** [comment]
And it works no more warning. Thanks 👍🏻
