### ISSUE TITLE
Disable/remove nginx for services that already provide a reverse proxy?

### ISSUE THREAD

**Issue by Nezteb** [PrivateBin/docker-nginx-fpm-alpine#144]
I'm deploying PrivateBin to https://fly.io/, and they have their own proxy setup, so if I can somehow disable/remove nginx from this Docker image that would be helpful!

I know the name of the image has nginx in the name, but I figured I'd ask anyway. 😄

**Comment by elrido** [comment]
Well, without nginx, nothing would serve the static resources that are needed to run the web UI (javascript & web-assembly application, CSS design, images, ...). You could theoretically attach this image as a [sidecar](https://www.containiq.com/post/kubernetes-sidecar-container) to your webserver of choice, so they would share the filesystem and the main container could serve these resources and proxy only the PHP-API requests into PHP-FPM.

If you would like to experiment with such a setup, you can disable the nginx in this image by attaching an empty file to this images [/etc/s6/services/nginx/run](https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/master/etc/s6/services/nginx/run), which should suppress s6 being able to launch the nginx service.

**Comment by Nezteb** [comment]
Yeah I figured removing nginx wouldn’t be ideal for the PHP setup but I wanted to ask anyway. 😄

I’ll try out your recommendations and see what happens. Thanks!

**Comment by elrido** [comment]
I have been tempted to explore an alternative setup, but do not yet have much experience with it. [Nginx now also offers unit](https://unit.nginx.org/) "a lightweight and versatile open-source server that has three core capabilities: it is a web server for static media assets, an application server that runs code in multiple languages, and a reverse proxy. It was built by nginx team members from scratch to be highly efficient and fully configurable at runtime." There is a package for it and the PHP 8.1 module in the alpine stable repositories and it's installed size is about half of the regular nginx package. Apart from being smaller, it would also reduce the setup to a single service, so we could eschew using the s6 service manager as well. Overall it would be less attack surface and less configuration we have to maintain, but it would be a breaking change, so if we'd want to experiment with it, we clearly would have to publish this as a separate namespace or tag as with the existing image some users will have made use of nginx and it's configuration options.

Should I revisit this idea (in a separate issue), I'll ping you here, in case you'd want to experiment with it.

**Comment by elrido** [comment]
Addendum: I've now got this prototyped in a forked repo. It does have [some limitations](https://github.com/PrivateBin/docker-unit-alpine#limitations) and I'll want to do some more testing on a production system with it. If anyone would like to test these, you can find the images documented at https://hub.docker.com/r/privatebin/unit-alpine and please raise any issues with these in the [forked repos issue tracker](https://github.com/PrivateBin/docker-unit-alpine/issues), until we know where to go with this.
