### ISSUE TITLE
Size limit not reflected in php.ini

### ISSUE THREAD

**Issue by Flightkick** [PrivateBin/docker-nginx-fpm-alpine#147]
Stumbling across this issue: https://github.com/PrivateBin/PrivateBin/issues/858
When increasing the `sizelimit`, these setttings also need to be applied to `php.ini`.

Currently, there doesn't seem to be an easy way to modify these settings in the Docker image.
The image doesn't contain a generic `/etc/php` symlink to the installed PHP version therefor it's not easy to attach a volume mount (volume mount needs to be specific, e.g.: `/etc/php81/...`)
It also doesn't look like these settings can be overridden through environment variables.

**Some possible solutions**
- Provide a symlink at `/etc/php` to the current version to allow volume bindings.
- Automate updating the required php.ini settings automatically accordingly to the `sizelimit` specified in Privatebin config.
- Allow configuration through environment variables.

**Comment by elrido** [comment]
The locations for attaching the configuration files (not only a php.ini, but also an nginx one) are [documented in the README.md file](https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/master/README.md#adjusting-nginx-or-php-fpm-settings). The following three values need to be tweaked:
https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/76251acdcf0e928645fcc3e040bd7dc79eb2b200/etc/php81/conf.d/00-docker.ini#L20-L22
https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/76251acdcf0e928645fcc3e040bd7dc79eb2b200/etc/nginx/nginx.conf#L66-L67

If anyone would like to raise a pull request with such an automation script, please write it in such a way that it detects a read-only filesystem at the directory of the config files, and doesn't fail the startup. The images are designed to run with a read-only filesystem, so currently any changes have to be attached from the outside into the image (ideally read-only as well).

For completeness, in the alternative nginx unit images, all three values can be set in a [single config file](https://github.com/PrivateBin/docker-unit-alpine/blob/master/conf.json) which would get attached to /var/lib/unit.

https://github.com/PrivateBin/docker-unit-alpine/blob/2b033dd6424025325971ec305d82f27248330b76/conf.json#L42-L43
https://github.com/PrivateBin/docker-unit-alpine/blob/2b033dd6424025325971ec305d82f27248330b76/conf.json#L63

**Comment by Flightkick** [comment]
@elrido Thanks for pointing that out. I completely missed that section, my bad.
Considering the read-only filesystem case there might not be an easy way to automatically propagate these settings. Attaching custom config files may be the most feasible solution.

Maybe adding a symlink at `/etc/php/` could provide a stable volume mount in case PHP upgrades are done.

**Comment by elrido** [comment]
The /etc/php stability would be a great idea! With alpine 3.18, the coming stable release, we will get access to php 8.2, so when we switch to that it might be a good opportunity to deal with this as well. I wonder if we can bind-mount into a symlink or would instead have to move the php8x dir and create a symlink in it's place. Will have to test this when we get there.

**Comment by elrido** [comment]
The /etc/php stability now got introduced in the image with tag `1.5.1-alpine3.18-php8.2`.
