### ISSUE TITLE
Unprivileged Image

### ISSUE THREAD

**Issue by Vacuois** [PrivateBin/docker-nginx-fpm-alpine#15]
Hello,

the current image set a required CAP on the NGINX binary (https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/master/Dockerfile#L53).
When running PrivateBin on a Kubernetes Cluster with hardened PSP, you might not have access to such CAP (which is required only to listen on port < 1024).

It could be nice to provide an image without this requirement for those of us with this kind of security constraints.

I rebuilt the image without the `setcap` line, and removed this line as well for our use case: https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/master/etc/nginx/sites-available/site.conf#L2

**Comment by elrido** [comment]
Yes, at the moment port 80 is only kept for backwards compatibility. I'll consider dropping that in the next image or by offering a second flavour of the image.

**Comment by elrido** [comment]
The no-CAP flavour got tagged `privatebin/nginx-fpm-alpine:1.3.4-alpine3.11-nocap-ipv6`.
