### ISSUE TITLE
Can be deleted.

### ISSUE THREAD

**Issue by Kyle5423** [PrivateBin/docker-nginx-fpm-alpine#159]
- Wrong repo

**Comment by elrido** [comment]
Assuming that CSS file is used by your selected template, you would attach your replacement CSS into /var/www/css/darkstrap-0.9.3.css - you can see in the Dockerfile that it is where the public files get unpacked into:

https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/5cc7453743fd387fa929f3f8b50b51d6549224af/Dockerfile#L67-L68
