### ISSUE TITLE
 Could not create paste: server error or not responding on Google Instance

### ISSUE THREAD

**Issue by keremcankabadayi** [PrivateBin/docker-nginx-fpm-alpine#165]
## Steps to reproduce

1. I installed Privatebin with Docker on Google Cloud.
2. Trying to create new bin throwing me error.

### What happens
I'm getting ` Could not create paste: server error or not responding`

### What should happen
It should create new bin.

## Additional information

I'm creating container with 
`docker run --name privatebin -d --restart="always" -u 0 -p 8099:8080 -v /data/privatebin:/srv/data privatebin/nginx-fpm-alpine`

![image](https://user-images.githubusercontent.com/23381187/83327171-99eb3c00-a282-11ea-8edb-e2d6500c94f6.png)
Console:
```
error Internal Server Error privatebin.js:4422:25
    run https://privatebin4455.kabadayiapps.tools/js/privatebin.js?1.3.4:4422
    jQuery 4
```
Network:
![image](https://user-images.githubusercontent.com/23381187/83327183-b12a2980-a282-11ea-9f30-100a947379ea.png)

I'm using Nginx Proxy Manager with Let's Encrypt. It exposes `443` port but i'm not using it. I exposed `22, 80, 443, 8099` at my instance.

Here my container

![image](https://user-images.githubusercontent.com/23381187/83327243-0c5c1c00-a283-11ea-87ab-c80e7d9b0277.png)
 
## Basic information

**Server address**:
`privatebin4455.kabadayiapps.tools`

**Server OS:**
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Webserver:**

**Browser:**
Firefox 76.0.1 (32-bit)

**PrivateBin version:**
1.3.4
I can reproduce this issue on <https://privatebin.net>: No

**Comment by rugk** [comment]
Note this is a docker issue, do transferred this repo. Anyway the exposed error should make it more clear and the permission issue is documented.

For improvements, feel free to submit a PR.
