### ISSUE TITLE
Nightly builds for multi-architecture images

### ISSUE THREAD

**Issue by zuh0** [PrivateBin/docker-nginx-fpm-alpine#17]
Hello,

I saw that you recently built a multi-architecture container image using `buildx`. I use arm64 and I would like to always have the latest image to stay up to date with security issues.

To stay up to date as much as possible and pull in updates from the `alpine` image and the software you install inside it, would it be possible to setup nightly builds with a GitHub action for example ? I would be willing to write and maintain an action using [this](https://github.com/marketplace/actions/docker-buildx) to have nightly automated builds.

**Comment by elrido** [comment]
Yeah, waiting for docker to finally implemente this on their cloud starts to look like a lost cause :-/ I'll check out the PR and tweak it to fit the use cases.

**Comment by zuh0** [comment]
@elrido I just tested the nightly image that was built tonight and it works fine on arm64 :smile:

**Comment by elrido** [comment]
Yes, that seemed to have worked just fine. Thank you very much for providing this solution!
