### ISSUE TITLE
docker image privatebin/fs:latest still includes zlib-1.2.13-1.js (instead of 1.3)

### ISSUE THREAD

**Issue by wivaku** [PrivateBin/docker-nginx-fpm-alpine#183]
The [latest template](https://github.com/PrivateBin/PrivateBin/blob/0581522414aa9f2b29cd6625e28c3150dd165ac1/tpl/bootstrap.php#L58) refers to v1.3
```
		<script type="text/javascript" data-cfasync="false" src="js/zlib-1.3.js" integrity="sha512-VL3lLnt8EexTr22ze4a4HfVghpgY48c/Lhf4CcQa8bgYaIRRPjV1nP7EA8RiciGoXXQ1IeiU7tjrclPeVEfxOQ==" crossorigin="anonymous"></script>
```

But the container (latest/nightly/edge) still contains v1.2.13-1:

```
docker exec privatebin ls -l js
...
-rw-rw-r--    1 nobody   www-data      5188 Dec 15 07:20 zlib-1.2.13-1.js
...
```

As a result custom templates that are based on the latest template will fail.

**Comment by rugk** [comment]
Which image (tag) are you executing?

Because the upgrade has not been deployed yet. [v1.6.2 still includes zlib v1.2.13-1](https://github.com/PrivateBin/PrivateBin/blob/d0420fb418669633f2dd4db1dee5681fb4201c16/tpl/bootstrap.php#L58).

So either wait for the update or use (copy) the template from the v1.6.2 version?

**Comment by wivaku** [comment]
ah that explains it. 
Tried edge/nightly/latest. 
No problem waiting

**Comment by elrido** [comment]
I hadn't planned on releasing again this soon, with only these two, seemingly, small changes:
https://github.com/PrivateBin/PrivateBin/blob/master/CHANGELOG.md#163-not-yet-released

Does the zlib 1.3 update warrant a new release? We can do one if there are good reasons for it. Your opinions, please?

**Comment by wivaku** [comment]
No worries. I use a custom template that is a patched version of the latest bootstrap.php template.
Was downloading from the latest commit on github, which (understandably) resulted in the issue.
Should have been copying from the downloaded container. Works fine now:
`docker cp privatebin:/srv/tpl/bootstrap.php ./template/bootstrap.php`

**Comment by rugk** [comment]
So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.
