### ISSUE TITLE
Webpage fails to load

### ISSUE THREAD

**Issue by BadCo-NZ** [PrivateBin/docker-nginx-fpm-alpine#19]
## Steps to reproduce

1. Install container
2. Run container
3. Open web page, and go to privatebin URL

### What happens
Web page fails to load

### What should happen
Web page should load

## Additional information

Originally I did have this working, but I was trying to get the conf.php file working and may have done something incorrectly.
Container log below.
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
s6-chown: fatal: unable to chown /var/run/s6/etc/services.d/php-fpm7/run: Operation not permitted
s6-chown: fatal: unable to chown /var/run/s6/etc/services.d/nginx/run: Operation not permitted
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2020/07/15 08:18:28 [warn] 182#182: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
[15-Jul-2020 08:18:28] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[15-Jul-2020 08:18:28] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[15-Jul-2020 08:18:28] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[15-Jul-2020 08:18:28] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[15-Jul-2020 08:18:28] NOTICE: fpm is running, pid 181
[15-Jul-2020 08:18:28] NOTICE: ready to handle connections
2020/07/15 08:22:14 [error] 197#197: *1 FastCGI sent in stderr: "PHP message: PHP Warning: parse_ini_file(/srv/cfg/conf.php): failed to open stream: No such file or directory in /srv/lib/Configuration.php on line 121PHP message: PHP Warning: array_key_exists() expects parameter 2 to be array, bool given in /srv/lib/Configuration.php on line 123PHP message: PHP Fatal error: Uncaught Exception: PrivateBin requires configuration section [main] to be present in configuration file. in /srv/lib/Configuration.php:124
Stack trace:
#0 /srv/lib/Controller.php(161): PrivateBin\Configuration->__construct()
#1 /srv/lib/Controller.php(121): PrivateBin\Controller->_init()
#2 /var/www/index.php(18): PrivateBin\Controller->__construct()

}
thrown in /srv/lib/Configuration.php on line 124" while reading response header from upstream, client: 172.21.0.14, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "paste.hardnet.nz"
172.21.0.14 - - [15/Jul/2020:08:22:14 +0000] "GET / HTTP/1.1" 500 5 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0" "101.98.39.190, 198.41.238.123"
2020/07/15 09:22:48 [error] 197#197: *3 FastCGI sent in stderr: "PHP message: PHP Warning: parse_ini_file(/srv/cfg/conf.php): failed to open stream: No such file or directory in /srv/lib/Configuration.php on line 121PHP message: PHP Warning: array_key_exists() expects parameter 2 to be array, bool given in /srv/lib/Configuration.php on line 123PHP message: PHP Fatal error: Uncaught Exception: PrivateBin requires configuration section [main] to be present in configuration file. in /srv/lib/Configuration.php:124
```

## Basic information

**Server address**: paste.hardnet.nz

**Server OS:** Unraid/Slackware

**Webserver:** nginx (via LS.io LetsEncrypt container)

**Browser:** FireFox 78.0.2

**PrivateBin version:** dockerhub version

I can reproduce this issue on <https://privatebin.net>: No

**Comment by elrido** [comment]
The important error is the top one in the PHP stack trace:
```
[...] PHP Warning: parse_ini_file(/srv/cfg/conf.php): failed to open stream: No such file or directory [...]
```
Since this file is optional and not part of the container image, I assume you did attach your own custom configuration file. Looking at the code, we do check if the file is readable, then try to open it:
https://github.com/PrivateBin/PrivateBin/blob/9914c37683496d161d9f8c8355bc89c358b1b243/lib/Configuration.php#L120-L121

According to the PHP docs for the [is_readable()](https://www.php.net/manual/en/function.is-readable.php) function, it caches the result - so this could happen if the file is present, but then removed. Or something is off with the permissions that tricks the is_readable check into passing, but prevents the file from getting read. Apparmor or Selinux might cause such behaviours.

If you are sure that the file is present in the container (you can exec /bin/ash in the container to explore the filesystem inside), you may have to change its ownership to match the userid of the processes running in the container, as is explained in the README:

> Note that the volume mounted must be owned by UID 65534 / GID 82. If you run the container in a docker instance with "userns-remap" you need to add your subuid/subgid range to these numbers.

**Comment by BadCo-NZ** [comment]
Yeah you pretty much nailed it. I have been having issues trying to mount the config directory an add the config file so ended up adding it then removing it and hence the error.

Thanks well the thorough response @elrido
