### ISSUE TITLE
Readme 'Custom Configuration' Inaccuracies

### ISSUE THREAD

**Issue by BadCo-NZ** [PrivateBin/docker-nginx-fpm-alpine#20]
Hi,

I have just been trying to deploy this docker image on unraid and tried following the below instructions for altering the config file.

> 
> Custom configuration
> 
> In case you want to use a customized conf.php file, for example one that has file uploads enabled or that uses a different template, add the file as a second volume:
> 
> `docker run -d --restart="always" --read-only -p 8080:8080 -v conf.php:/srv/cfg/conf.php:ro -v privatebin-data:/srv/data privatebin/nginx-fpm-alpine`
> 
> Note: The Filesystem data storage is supported out of the box. The image includes PDO modules for MySQL, PostgreSQL and SQLite, required for the Database one, but you still need to keep the /srv/data persisted for the server salt and the traffic limiter.
> 

Unfortunately that never worked for me. So after some contemplating I wiped the container, mounted the /srv/cfg folder and added the sample conf.php to this directory, changed file uploads to true, restarted the container, and it finally worked.

`-v '/mnt/user/appdata/privatebin/cfg':'/srv/cfg':'rw'`

**Comment by elrido** [comment]
That works just fine - I use this mechanism frequently to mount single configuration files into containers. Are you sure you can rule out permission problems?

You can start the container using the described command into the background - it will show you the running containers ID. Then you can launch a shell in the running container and inspect the configuration file:
```shell
docker exec -ti <ID of your running container> /bin/ash
ls -l /srv/cfg/conf.php
less /srv/cfg/conf.php
```
Do the permissions look readable? Can you read the file as the user in the container? You may have to change the owner UID of the configuration file from outside of the container (mounting the file read-only and the non-root user will prevent you from manipulating the permissions from inside the container).

**Comment by elrido** [comment]
Thank you for that update! Indeed, docker doesn't like relative paths in the volume parameters and so I changed the documentation to include the `$PWD` environment variable, that will be set to the absolute path of the current directory in bash shells. Hope this prevents future users from running into this issue.

**Comment by BadCo-NZ** [comment]
> 
> 
> That works just fine - I use this mechanism frequently to mount single configuration files into containers. Are you sure you can rule out permission problems?
> 
> You can start the container using the described command into the background - it will show you the running containers ID. Then you can launch a shell in the running container and inspect the configuration file:
> 
> ```shell
> docker exec -ti <ID of your running container> /bin/ash
> ls -l /srv/cfg/conf.php
> less /srv/cfg/conf.php
> ```
> 
> Do the permissions look readable? Can you read the file as the user in the container? You may have to change the owner UID of the configuration file from outside of the container (mounting the file read-only and the non-root user will prevent you from manipulating the permissions from inside the container).

Sorry I never got back to you, Covid has me over-run at work.
