### ISSUE TITLE
Make a release to include the latest security patches

### ISSUE THREAD

**Issue by dotdc** [PrivateBin/docker-nginx-fpm-alpine#208]
Hi @elrido,

After noticing a security alert, I updated privatebin from `1.7.4-alpine3.20.2` to `1.7.5-alpine3.20.3`, but I still have several critical vulnerabilities that I would be happy to fix.
Do you think we can make a release to include the latest security patches?

Thank you in advance.

Vulnerabilities:

Tag 1.7.4-alpine3.20.2 :
```
$ trivy image privatebin/nginx-fpm-alpine:1.7.4-alpine3.20.2
[...]
Total: 128 (UNKNOWN: 0, LOW: 16, MEDIUM: 44, HIGH: 54, CRITICAL: 14)
[...]
```

Tag 1.7.5-alpine3.20.3 :
```
$ trivy image privatebin/nginx-fpm-alpine:1.7.5-alpine3.20.3
[...]
Total: 65 (UNKNOWN: 0, LOW: 0, MEDIUM: 26, HIGH: 26, CRITICAL: 13)
[...]
```

Tag latest :
```
$ trivy image privatebin/nginx-fpm-alpine:latest
[...]
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
[...]
```

**Comment by elrido** [comment]
I intend to tag another image when alpine:3.21 got released (the current `edge`) and we have switched to this in our Dockerfile (that will be labeled `1.7.5-alpine3.21`).

At any time you can either use the `latest` tag (if using a solution that auto-updates your containers for you) or simply look up and use the sha256 hash of the current `latest` image that has the php 8.3 issues resolved. You may also consider switching to the more lightweight [nginx unit images](https://hub.docker.com/r/privatebin/unit-alpine/), which contain less moving parts.

For example, the [tag page on docker hub](https://hub.docker.com/r/privatebin/nginx-fpm-alpine/tags) tells us that the amd64-CPU-architecture image currently tagged as `privatebin/nginx-fpm-alpine:latest` (at the time of writing this) is `privatebin/nginx-fpm-alpine@sha256:18cb2f6ee432`.

**Comment by dotdc** [comment]
Sounds great! 
Will check the differences with unit-alpine, but it has the same flaws linked to php 8.3.13.

```
$ trivy image privatebin/unit-alpine:1.7.5-alpine3.20.3
[...]
Total: 65 (UNKNOWN: 0, LOW: 0, MEDIUM: 26, HIGH: 26, CRITICAL: 13)
[...]
```

Closing issue, thanks!

**Comment by elrido** [comment]
With alpine 3.21 now released, I've updated the dockerfile and tagged `1.7.5-alpine3.21`, images should now be available.
