### ISSUE TITLE
How to mount conf.php as second volume

### ISSUE THREAD

**Issue by StifflersMoM69** [PrivateBin/docker-nginx-fpm-alpine#23]
Hi, i installed this docker container on my Synology NAS. Could you please help me how to mount the custom conf.php

i mounted the file like this
file: docker/privatebin/conf.php
mount-point: /conf.php
permission: rw

but i cant see my changes. 

Thanks, for helping me out.

**Comment by elrido** [comment]
Could you try to use an absolute path for the file (one that starts at the root / of the filesystem)? As [discussed in another issue](https://github.com/PrivateBin/docker-nginx-fpm-alpine/issues/20#issuecomment-683382213), docker does unexpected things if you don't use an absolute path. If it works, I would recommend to attach that file "ro", as PrivateBin should normally not write to it.

**Comment by StifflersMoM69** [comment]
Hi elrido,

thanks for for the hint.
I was not able to modify the path within the Synology GUI of docker, but i mounted the folder too and it worked. So if anyone else is running into this issue her are the settings i made

folder: docker/privatebin
mount-point: /srv/cfg
permission: ro

file: docker/privatebin/conf.php
mount-point: /conf.php
permission: ro
