### ISSUE TITLE
conf.php example doesn't seem to work

### ISSUE THREAD

**Issue by tomlawesome** [PrivateBin/docker-nginx-fpm-alpine#34]
## Steps to reproduce

1. Install private bin
2. Copy to installation and restart

### What happens
Page fails to load properly

### What should happen
Page should load in a normal manner with a default set of options that can then be tweaked

## Additional information
Using docker, I mount conf.php in /srv/cfg/conf.php since my index.php has /srv/ listed as the location for data

conf.php is populated with a carbon copy of conf.php

## Basic information
(not my pb instance!)
https://paste.d4v.is/?b7ff7bb935007854#2vp6RrXCAKTQXcetD8yeZ3MymjkUJo8Dz1HXGSfM2gMf

Screenshots:
with conf.php mounted:
https://i.ibb.co/q1nSdpk/pberror1.png

without conf.php mounted:
https://i.ibb.co/Mgs0CNZ/pberror2.png

**Server address**:

**Server OS:**
Debian10

**Webserver:**
PB docker image + traefik

**PrivateBin version:**
Latest container

I can reproduce this issue on <https://privatebin.net>:  No, not relevant

I apologise if this is user error (it almost certainly is) but I have been struggling with it for a while now and as such can only use PB in the default config where I don't specify conf.php. 

I have tried editing conf.php in every way I can think of to try and get it to load and it does not. I have also tried editing ./lib/Configuration.php directly and no joy.

**Comment by rugk** [comment]
I've also moved the issue to the Docker image repo, given it looks like a Docker issue. Feel free to correct me if that is wrong…

**Comment by tomlawesome** [comment]
Hi both, 

thanks so much for your time/help. As suspected this was a user error. I must have missed somewhere that conf.php needed those user perms. Have updated this morning and the site is now functioning as expected, hooked up to Postgres etc with my info. 

Fantastic. Thanks again for all the support/hard work!
