### ISSUE TITLE
stuck at [fix-attrs.d] applying ownership & permissions fixes...

### ISSUE THREAD

**Issue by GiamBoscaro** [PrivateBin/docker-nginx-fpm-alpine#37]
I am trying to run a privatebin docker in my raspberry pi 4 with 64 bits OS.

I tried different tags and the container is always stuck at `[fix-attrs.d] applying ownership & permissions fixes...`

Any suggestion? 

Regards

**Comment by GiamBoscaro** [comment]
I runned the "edge" tag and it's working fine, but all the previous tags don't work. Edge shouldn't be stable thought, but I am ok with it for the moment. Hoping for a new stable version

**Comment by elrido** [comment]
Sorry for the late reply. The `[fix-attrs.d]` message is the last message that is part of the s6 overlay startup. As long as no requests are made, there won't be any further messages in the logs at that point.

Each request to the service should produce further log lines, one for each request that nginx processes (the one for the web app plus all the js, css and image files).

php-fpm is configured to only log errors. For example, if you attach a volume for the data that isn't writeable to the php-fpm process, trying to save a paste will result in an exception getting logged by the php-fpm process, telling you about the issue.

**Comment by elrido** [comment]
FYI, with alpine 3.14 released, we got our images rebuilt and the `1.3.5-alpine3.14`, `1.3.5` and `latest` tags now all contain the fixed s6 for armv7.
