### ISSUE TITLE
Add two storage backend flavours of the image: filesystem-backend-only image and GCS image

### ISSUE THREAD

**Issue by elrido** [PrivateBin/docker-nginx-fpm-alpine#41]
The current image supports both the default filesystem and the optional Postgres and MySQL PDO backends. The Google Cloud Storage backend, which was recently added in the development branch of PrivateBin, requires the installation of a relatively large PHP library, which is not included in the PrivateBin release.

In order not to break current behaviour, I suggest we keep the current "default" image tags as they are and let this serve as the "DB backend" flavour. In addition, we could also publish two additional flavours:
1. An image without the PDO modules, only supporting the filesystem backend. This lowers the size and attack surface of the image.
2. An image without the PDO modules, but including the library needed for the Google Cloud Storage backend.

This is related to #40 in that we should consider these 3 flavours in a tag naming scheme. One idea could be to add a suffix for the two backend flavours, for example:

| image type / storage backend   | PDO     | filesystem only    | GCS               |
|--------------------------------|---------|--------------------|-------------------|
| release (on alpine stable)     | 1.3.5   | 1.3.5-file-store   | 1.3.5-gcs-store   |
| edge (release on alpine edge)  | edge    | edge-file-store    | edge-gcs-store    |
| nightly (dev on alpine stable) | nightly | nightly-file-store | nightly-gcs-store |

Does anyone have suggestions for such suffixes? Do suffixes make sense or would another scheme to distinguish the image flavours make more sense?

**Comment by rugk** [comment]
…or you configure the container once at startup with some tags, where SQL access data etc. is included. Likely, you'd want to use some `entrypoint` scripts for that.

That is e.g. how Nextcloud does it: https://github.com/nextcloud/docker/blob/master/docker-entrypoint.sh

The advantage would be you don't need a tag for each storage version, but can keep those to refer to the version.

**Comment by elrido** [comment]
The reason the images don't use entrypoint scripts that change the internals of the container is that the image is intended to work when attached read-only and also with any non-root user ID (a random user ID is the default on OpenShift, for example). This means we can't install packages or change any of the configuration files on container startup. Hence the need to provide several image tags with the different features "baked in".

Of course, we could also extend the existing image to include the GCS library - it would then support all three storage options. It would increase the image size by about 3.5 MiB (it currently is 34.4 MiB, uncompressed). This wouldn't break any existing use cases either. We could do that as a short term solution, until someone raises an issue on the size of the image or the reduction of the attack surface. Then we could still provide a more minimal image via tag.

**Comment by rugk** [comment]
I dunno… multiple images sounds fine, too. :shrug: 

Or one image for the GCS stuff…

**Comment by mvanholsteijn** [comment]
I would recommend putting the flavor into the image name. These are distinctly different images and avoids accidental mixups. 

You can use a suffix privatebin-pdo:1.3.5, privatebin-fs:1.3.5 and privatebin-gcs:1.3.5 or use the dockerhub namespace,  privatebin/pdo:1.3.5, privatebin/fs:1.3.5, privatebin/gcs:1.3.5.

My personal preference would be the latter.

**Comment by rugk** [comment]
That said `privatebin-pdo` and `privatebin-fs` could be one image – it's just some minor configuration difference between these two…

**Comment by mvanholsteijn** [comment]
true.

**Comment by elrido** [comment]
I like the idea with the additional images for the flavours and using the dockerhub namespace as part of the name. And we could add GCS support into the current image, making it generic, though larger.

I'll investigate how to set this up using a single repository - the logic in the github action starts to get a bit verbose anyway, so it might be time for a build script to handle it all.

**Comment by mvanholsteijn** [comment]
Currently the mage supports GCS, the FileSystem and the two SQL backends. I guess this ticket can be closed.

**Comment by rugk** [comment]
The question would be whether we'd want a Docker image version _without_ all GCM stuff (which probably/likely only a minority of our users actually use…).

**Comment by elrido** [comment]
This is still pending, I just haven't come around to conclude it yet. As described above the plan is to keep the existing image with all modules and libs so there are no regressions for existing users and then introduce three flavours in different namespaces that only contain the necessary bits.

I did the first part of the work but didn't yet find time to do all the rest. Plus there was some discussion among the maintainers to take this opportunity to also publish these into a different registry as a fallback in case docker hub has an outage - I have to investigate that aspect as well.

**Comment by mvanholsteijn** [comment]
> ... Plus there was some discussion among the maintainers to take this opportunity to also publish these into a different registry as a fallback in case docker hub has an outage - I have to investigate that aspect as well.

Perhaps the GitHub container registry is a good alternate location. https://github.blog/2020-09-01-introducing-github-container-registry/

**Comment by rugk** [comment]
>  to take this opportunity to also publish these into a different registry as a fallback in case docker hub has an outage

Yes, I see this unrelated to this issue though. I.e. the things can be solved separately…
Though we could also discuss that here publicly in a GitHub issue.

And yes @mvanholsteijn we've also thought about GitLab's registry.

**Comment by mvanholsteijn** [comment]
If you checkout PR #55: it has buildx.sh create 4 different container images inside the namespace.

**Comment by elrido** [comment]
Resolved with PR #55 and some subsequent commits:
- [Image for file based storage](https://hub.docker.com/r/privatebin/fs)
- [Image for PostgreSQL, MariaDB & MySQL](https://hub.docker.com/r/privatebin/pdo)
- [Image for Google Cloud Storage](https://hub.docker.com/r/privatebin/gcs)
