### ISSUE TITLE
Latest image seems to have broken custom conf.php

### ISSUE THREAD

**Issue by TSLETSGO** [PrivateBin/docker-nginx-fpm-alpine#50]
Hi, just sending a little headsup regarding breakage of custom conf.php's in latest image.
- The latest container image seems to have broken custom conf.php configurations and just ignores the conf.php file entirely.
- Image tag "1.3.5" seems to be the latest working container image where a custom conf.php is working just fine.

**Info about test environment:**

**Volume mount:**
`
-v $CONTAINERS/privatebin/cfg/conf.php:/srv/cfg/conf.php:ro \
`
**Output of ls -la within container to highlight permissions:** 
`-r--------    1 nobody   www-data      7396 Jul  4 01:23 conf.php`

As previously mentioned, it works just fine on image tag 1.3.5 and previous versions.

**Comment by TheWiresharkGuy** [comment]
Hi, same problem here!

**Comment by elrido** [comment]
Broken in #38
