### ISSUE TITLE
Update docker image to PrivateBin 1.3

### ISSUE THREAD

**Issue by bdashrad** [PrivateBin/docker-nginx-fpm-alpine#6]
PrivateBin [1.3 has been released](https://github.com/PrivateBin/PrivateBin/releases/tag/1.3), so we should update the docker image.

**Comment by elrido** [comment]
I'm in the middle of the release, don't worry, will do this tonight. Need this image for the demo site, but needed to sign the release first.

**Comment by bdashrad** [comment]
I mostly commented here so I could have a reminder to do the helm-chart when it's updated

**Comment by elrido** [comment]
image is [live](https://cloud.docker.com/repository/docker/privatebin/nginx-fpm-alpine/tags) (and [works](https://privatebin.net/))

**Comment by gerroon** [comment]
@elrido

Any process to upgrade it beside pulling?

**Comment by elrido** [comment]
Depends on your setup - The demo site for example had everything set to defaults (no configuration file) and so I just needed to switch out the container images. In another site I had used a configuration file and needed to update the cspheader (I actually removed it from the config file, as the default value was fine).

Note that the last 1.2.1 image version (the one with alpine 3.10 base) changed the UID for the php-fpm process to nobody, so if you upgrade from an older 1.2 or 1.2.1 image you need to `chown` your data directory recursively as [described in the README](https://github.com/PrivateBin/docker-nginx-fpm-alpine/commit/c1bcafcc020c331187d3b4d48084d9802ade5b06#diff-04c6e90faac2675aa89e2176d2eec7d8R23).

**Comment by gerroon** [comment]
@elrido

Thanks, I  got it to work however one issue. The page does not load in Firefox. I use https://github.com/pyllyukko/user.js with Firefox I wonder if something there is blocking it ? I am using FF 67 on Linux

**Comment by elrido** [comment]
To conclude this and duplicate the information learned over in the main projects ticket:
- Web assembly is a requirement for 1.3 and all major browser (except IE) have support for this as of mid 2017.
- The above linked [user.js disables web assembly](https://github.com/pyllyukko/user.js/blob/master/user.js#L198) in Firefox, so that particular setup is not compatible with privatebin 1.3 anymore.
