### ISSUE TITLE
Problem running version 1.3.5-alpine3.14.2

### ISSUE THREAD

**Issue by bengtfredh** [PrivateBin/docker-nginx-fpm-alpine#66]
When container is starting it give following message:
`s6-linux-init: fatal: unable to copy /etc/s6-linux-init/current/run-image to /run: Operation not permitted`

When I revert to 1.3.5-alpine3.13 all run fine.

**Comment by elrido** [comment]
Could you share some details on the used container runtime version (i.e. `docker info` output) and command line / yaml file for launching the container image? Does it also happen with 1.3.5-alpine3.14-short?

**Comment by bengtfredh** [comment]
I run podman. 1.3.5-alpine3.14-short is working fine.

With latest:
Command:
```
podman run --name privatebin --read-only -v /opt/privatebin/conf.php:/srv/cfg/conf.php:ro -v /opt/privatebin/data:/srv/data:z --env-file /opt/privatebin/privatebin.env -p 127.0.0.1:8000:8080 --pull=always docker.io/privatebin/nginx-fpm-alpine:latest
```
Output:
```
Trying to pull docker.io/privatebin/nginx-fpm-alpine:latest...
Getting image source signatures
Copying blob a0d0a0d46f8b skipped: already exists  
Copying blob 00283295b935 skipped: already exists  
Copying blob bbdb7b8736ef skipped: already exists  
Copying blob 89b95a3e63c7 [--------------------------------------] 0.0b / 0.0b
Copying config 2483191ad9 done  
Writing manifest to image destination
Storing  #signatures
s6-linux-init: fatal: unable to copy /etc/s6-linux-init/current/run-image to /run: Operation not permitted
```

**Comment by elrido** [comment]
I haven't yet had the chance to work with podman. Could you check, inside of the container, if the `/run` volume is read-write? A workaround, if not, would be to attach a tmpfs to that location.
https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/fa2d71bd8a2d5df4fad0d46c3bba9440c8ee3cb0/Dockerfile#L88-L89

**Comment by bengtfredh** [comment]
I did some changes to command line today, and now latest run fine. New version of image got pulled down, so can not say for sure if it is the new version or my changes to command line.
```
podman run --name privatebin --read-only -v /opt/privatebin/conf.php:/srv/cfg/conf.php:ro,Z,U -v /opt/privatebin/data:/srv/data:Z,U --env-file /opt/privatebin/privatebin.env -p 127.0.0.1:8000:8080 --pull=always docker.io/privatebin/nginx-fpm-alpine:latest
```
