### ISSUE TITLE
File upload limitations

### ISSUE THREAD

**Issue by vmazyliukTW** [PrivateBin/docker-nginx-fpm-alpine#7]
By default in conf.php sizelimit = 2Mb. 
Which is easy to override.
But there are also nginx and php limitations regarding this.
And it's not so easy to fix that. 
Could you please change
 - upload_max_filesize 
 - post_max_size

in php.ini and also add
 - client_max_body_size 

parameter in nginx config with some reasonable value (like 500-1000M)?

I can create PR if needed.

**Comment by elrido** [comment]
I don't think this is safe to enable this by default - remember that this will allocate memory and temporary files in the size of the uploaded file, on the server and memory on the browser, while it is being processed. This is a major risk to overload the server, by just sending a few large files in parallel until the disk runs full. I would be OK with increasing it to 10 or 15 MiB, but 500 or 1000 is bound to get someone in trouble sooner or later. Do you really need it to be that high?

On the other hand, it is pretty simple to override these values by attaching appropriate configuration files into the containers /etc/nginx/conf.d/ and /etc/php7/conf.d/ folders to be picked up. How about we document this in the README?

**Comment by vmazyliukTW** [comment]
Hey!
Yeah if you document this in README it would be great thanks!

**Comment by elrido** [comment]
With the 1.3.1 release the default was increased to 10 MiB, so the values got increased for that, plus documentation got added on where to attach overriding configuration files for nginx and php-fpm.
