### ISSUE TITLE
After I auto-update to newest pulled image, I recieved error message

### ISSUE THREAD

**Issue by yche2990** [PrivateBin/docker-nginx-fpm-alpine#75]
I cannot start with the following error:

<html>
<body>
<div class="x-grid3-row x-grid3-row-selected" role="row" id="ext-gen20384" style="margin: 0px; padding: 0px; cursor: default; border-width: 0px 0px 1px; border-style: dotted dotted solid; border-top-color: initial; border-right-color: initial; border-bottom-color: rgba(198, 212, 224, 0.4); border-left-color: initial; border-image: initial; width: 1337px; background-color: rgba(5, 127, 235, 0.1) !important; color: rgb(65, 75, 85); font-size: 13px; font-family: Verdana, Arial, &quot;Microsoft YaHei&quot;, sans-serif; font-style: normal; font-variant-ligatures: none; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">

2021/10/09 23:43:26 [emerg] 17#17: unknown directive "add" in /etc/nginx/http.d/site.conf:25 | stdout
-- | --

</div>
</body>
</html>

**Comment by andrem1987** [comment]
I have the same problem. In the `/etc/nginx/http.d/site.conf` on Line 25 is the failure: it has to be `add_header` instead of `add header`.

**Comment by rugk** [comment]
Introduced by #74 apparently. Next time, feel free to directly create a PR to fix it.

Our CI did not catch this, as it apparently does not start the image. I opened https://github.com/PrivateBin/docker-nginx-fpm-alpine/issues/76 for this.

**Comment by sylr** [comment]
Geez, sorry about that guys :sweat:
