### ISSUE TITLE
Smoke test for Docker image

### ISSUE THREAD

**Issue by rugk** [PrivateBin/docker-nginx-fpm-alpine#76]
To catch errors such as https://github.com/PrivateBin/docker-nginx-fpm-alpine/issues/75, I propose our CI should also start the image and do some sort of smoke-test or so that the image is actually startable.

E.g. start the image, do some curl on the port.

This could e.g. be implemented as `health_check` (not to be delivered though, e.g. in a docker-compose or just CLI stuff) or just a shell script…

**Comment by elrido** [comment]
I have a number of ideas on how to implement some basic testing, once the container got launched. The thing I'm not sure how to do or if it is possible is if we can use the CPU emulation that docker buildx uses for building non-amd64 images to also run them in the amd64 based github action environment. Any pointers on how to do that are most welcome.

Apart from that, some of the tests that I'd do would be roughly along these lines:
```
sleep 5 # to give the services time to start up and the log to collect any errors that might occur
docker ps ... # check that the container is still up and running
curl --silent --show-error -o /dev/null http://localhost:8080/
docker logs ... | ! grep --silent "warn|emerg|fatal|panic" # check that there are no issues in the logs (--invert-match doesn't work with --silent, as it would exit on the first "non-error"
```

**Comment by rugk** [comment]
> The thing I'm not sure how to do or if it is possible is if we can use the CPU emulation that docker buildx uses for building non-amd64 images to also run them in the amd64 based github action environment.

Hmm do you really think this is needed? Should not containers absract away most system issues, so does it really matter in which env it is running?

IMHO I would already be fine if that check was done on _any_ architecture :upside_down_face:
