### ISSUE TITLE
Push images to alternative registry (eg. Github Container Registry)

### ISSUE THREAD

**Issue by samip5** [PrivateBin/docker-nginx-fpm-alpine#85]
I would like to request that the Github Action to push images would be updated to also push to Github Container Registry, to bypass Docker Hub's pull limits.

https://developers.redhat.com/blog/2021/02/18/how-to-work-around-dockers-new-download-rate-limit-on-red-hat-openshift#:~:text=Docker%27s%20new%20rate%20limit,-Docker%20recently%20changed&text=The%20company%20now%20has%20a,from%20a%20single%20IP%20address.

**Comment by rugk** [comment]
Ah thanks. Yeah we discussed it internally already (for maintainers, see https://github.com/orgs/PrivateBin/teams/maintainers/discussions/19), but nothing happened yet there.

It should be quite simple to integrate it into teh CI.
I did something similar here:
https://github.com/rugk/container-web-static-compressor/blob/41a15429a86c002d4f4a11b90262a49c2cad224a/.github/workflows/docker-ci.yml#L58-L74

(It pushed to Docker Hub and the selected part to GitHub Containers)

**Comment by samip5** [comment]
> Ah thanks. Yeah we discussed it internally already (for maintainers, see https://github.com/orgs/PrivateBin/teams/maintainers/discussions/19), but nothing happened yet there. And indeed your argument is a very good one, actually.

That's not visible for us non-org members.

**Comment by rugk** [comment]
Yes, I'll provide a summary.

So everything has been said already, apart from that, we've also discussed some other registries. 
So other interesting registries to consider are:
* https://quay.io/ – AFAIK also quite simple to push
* https://registry.fedoraproject.org/ - though for that, we may have to integrate that into the Fedora system (likely a Fedora base image) and you'd AFAIK need to be a Fedora package maintainer, so e.g. only Fedora's `privatebin-server` (if that exists, I did not check it) or so could be published there.

**Comment by elrido** [comment]
@Zoey2936, your change worked and the nightly images got published to https://github.com/orgs/PrivateBin/packages - Some jobs failed with 403 authentication errors during the push to ghcr and I re-ran those manually to ensure we have a full set of images.

I will now tag the latest commit as 1.5.1-alpine3.17.2-ghcr and push the tag to trigger the tagged images getting re-built and pushed there as well. To conclude this issue, I think we should also document the new location(s) in the README - I'll prepare a pull request for you all to comment on.
