### ISSUE TITLE
Cannot create pastes after updating to latest 1.3.5 GCS Image

### ISSUE THREAD

**Issue by cwilson21** [PrivateBin/docker-nginx-fpm-alpine#86]
Updated my privatebin instance that is running in Google Cloud Run  to the latest  version of the GCS image, and it no longer creates pastes. 

When you click submit on the site it displays the following error: 

` Could not create paste: server error or not responding`

In the Cloud Run logs the following error is displayed:

```2022-01-11T22:31:17.075418Z2022/01/11 22:31:16 [error] 15#15: *17 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught TypeError: forward_static_call(): Argument #1 ($callback) must be a valid callback, class "PrivateBin\Data\GoogleCloudStorage" not found in /srv/lib/Model.php:85 Stack trace: #0 /srv/lib/Model.php(85): forward_static_call() #1 /srv/lib/Model.php(71): PrivateBin\Model->_getStore() #2 /srv/lib/Controller.php(257): PrivateBin\Model->purge() #3 /srv/lib/Controller.php(125): PrivateBin\Controller->_create() #4 /var/www/index.php(18): PrivateBin\Controller->__construct() #5 {main} thrown in /srv/lib/Model.php on line 85" while reading response header from upstream, client: 169.254.8.129, server: , request: "POST / HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "--"```

Config is : 

````
[main]
name = "Develop PrivateBin"
discussion = true
opendiscussion = false
password = true
fileupload = true
burnafterreadingselected = true
defaultformatter = "plaintext"
sizelimit = 10485760
template = "bootstrap"
languageselection = false

[expire]
default = "1day"

[expire_options]
5min = 300
10min = 600
1hour = 3600
1day = 86400
1week = 604800
1month = 2592000

[formatter_options]
plaintext = "Plain Text"
syntaxhighlighting = "Source Code"
markdown = "Markdown"

[traffic]
limit = 0

[purge]
limit = 600
batchsize = 10

[model]
class = GoogleCloudStorage

[model_options]
bucket = "privatebin-development"
```

**Comment by cwilson21** [comment]
So using the image from docker hub that specifically states that it is for GCS use is not viable for use with GCS?

https://hub.docker.com/r/privatebin/gcs

**Comment by elrido** [comment]
Obviously we had to prepare the image build before a release of the software with support for it (chicken/egg). The developer adding that feature also needed this, in order to validate it worked on a live GCS, so they kindly provided the support for producing it here. Once a future release of PrivateBin with the GCS support is made, the GCS image published at that point will be viable for GCS.

**Comment by iJebus** [comment]
That probably could have been clearer in the documentation. Cool that it's coming though 🎉

**Comment by elrido** [comment]
As the question seems to have been answered, I'll close the ticket.

**Comment by elrido** [comment]
FYI, the 1.4.0 release has now finally happened and the GCS images should now have become functional.
