### ISSUE TITLE
Crashes on Ubuntu 22.04 amd64 host

### ISSUE THREAD

**Issue by ViRb3** [PrivateBin/docker-nginx-fpm-alpine#97]
This is what I get:
```
cp: can't create directory '/run/services': Permission denied
s6-svscan: fatal: unable to chdir: No such file or directory
```

I use `privatebin/nginx-fpm-alpine:1.4.0`.

**Comment by elrido** [comment]
By default, at least on docker, marking the directories as `VOLUMES` allows them to be written into:
https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/4ae270e02a4273b7eb9ac4ef32de33e313efefef/Dockerfile#L89-L90

Over with the [helm chart](https://github.com/PrivateBin/helm-chart/pull/71), we have received reports that indicate that some (newer?) container runtimes don't do that (anymore). The suggested solution is to attach the appropriate volumes manually. I'd recommend using a tmpfs on /run and /tmp and a filesystem backed volume on /var/lib/nginx/tmp.

For reproducing your issue and diagnosing it further, could you share what container runtime (docker, podman, something else) your using and what version of it, please?

**Comment by ViRb3** [comment]
Thanks a lot for getting back to me. Here's some versions:
```bash
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy

# docker --version
Docker version 20.10.12, build 20.10.12-0ubuntu4

# docker-compose --version
docker-compose version 1.29.2, build unknown

# containerd --version
containerd github.com/containerd/containerd 1.5.9-0ubuntu3
```

This is the official distro Docker, installed via:
```bash
apt install docker.io docker-compose
```

**Comment by ViRb3** [comment]
In fact, the issue was actually that I migrated my volumes over from Ubuntu 21.10. After I cleared all privatebin volumes, everything works now. Sorry for the noise!
